# Package Development {.unnumbered}

overview (half my thesis is finishing `dsbox` package). background on what the package attempts to do "The goal of dsbox is to supplement the Data Science Course in a Box project. The package contains the datasets that are used in the materials in Data Science Course in a Box as well as the learnr tutorials." - https://rstudio-education.github.io/dsbox/index.html

explain the larger Data Science in a Box project, https://datasciencebox.org, basically condensing all the curriculum material here into 10 freestanding, interactive, automatically-graded `learnr` tutorials

## Phase 1: Initial tidying work

--first time ever with pull requests and learnr, ie more than just basics in the RStudio window
--as well as roxygen and rds files
--change question wording to be more clear, and feedback in places to get graduaally more scaffolded
--chnage links in codebooks, notice an exercise wasnt making sense and looked at codebook and saw levels of a variable was coded the wrong way

## Phase 2: Creating a new tutorial

--there were nine tutorials when it existed
--the only HW assignment from DS in a box that hadnt been converted yet had to do with Dennys and LaQuinta data, and skeleton documents for the data already existed in dsbox
--thought critically about how to convert that hw into a tutorial, changed pacing to make it better as a standalone and interactive

## Phase 3: CRAN submission

--goal was to submit to CRAN, explain CRAN
--learned a lot about package checks/github actions
--had been away from it for so long, first thing this semester was to update the version numbers of all the github actions checks
--also had to update to base pipe, it had been that long
--that spurs conversation about DESCRIPTION and NAMESPACE files. did research on how other tutorial packages handled the "Depends" "Suggests" and "Requires" fields.
--stuff like spell check, standardizing to American English, decreased sizes of cover photos for each tutorial to fit on CRAN
--eventually hitting final road block of `learnr` not being fully available on CRAN, thus our package that would want to Depend it can't