project:
  type: book
  output-dir: docs
book:
  title: "Exploring Data Science Education: From Tutorials to Assessment"
  subtitle: "Duke Statistical Science | Graduation with Distinction"
  favicon: figs/logo.png
  date: last-modified
  date-format: long
  author: 
    - Evan Dragich
    - supervised by Dr. Mine Çetinkaya-Rundel, PhD.
  chapters:
    - index.qmd
    - thesis-intro.qmd
    - background.qmd
    - development.qmd
    - package.qmd
    - discussion.qmd
    - bibliography.qmd
    - instrument.qmd
    - graveyard.qmd
    - package-examples.qmd

execute:
  echo: false
  warning: false

bibliography: thesis.bib
nocite: |
  @*

format:
  html:
    theme: litera
    toc: true
    toc-depth: 2
    number-depth: 0
    css: styles.css
    grid:
      sidebar-width: 350px
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 2
    number-depth: 0
    include-in-header: 
      text: |
        \usepackage{mdframed}


