project:
  type: book
  output-dir: docs
book:
  title: "Exploring Data Science Education: From Tutorials to Assessment"
  subtitle: "Duke Statistical Science | Graduation with Distinction"
  output-file: "Exploring-Data-Science-Education-From-Tutorials-to-Assessment"
  date: today
  date-format: long
  author: 
    - Evan Dragich
    - supervised by Mine Çetinkaya-Rundel, PhD.
  chapters:
    - index.qmd
    - introduction.qmd
    - background.qmd
    - development.qmd
    - package.qmd
    - discussion.qmd
    - bibliography.qmd
    - instrument.qmd
    - graveyard.qmd
    - package-examples.qmd
  navbar:
    right:
      - icon: download
        href: https://github.com/evandragich/thesis-work/raw/main/docs/Exploring-Data-Science-Education-From-Tutorials-to-Assessment.pdf
        aria-label: Download PDF
      - icon: file-slides
        href: https://evandragich.quarto.pub/thesis-slides/
        aria-label: View Presentation Slides
      - icon: github
        href: https://github.com/evandragich/thesis-work
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/evandragich/
        aria-label: LinkedIn
    page-footer:
      left: 
        - text: "Copyright 2023, Evan Dragich"
        
  search:
    location: navbar
    type: overlay

execute:
  echo: false
  warning: false

bibliography: thesis.bib
nocite: |
  @*
  

format:
  html:
    theme: litera
    toc: true
    toc-depth: 2
    number-depth: 0
    css: styles.css
    grid:
      sidebar-width: 350px
      body-width: 900px
    include-in-header: favicon.html
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 2
    number-depth: 0
    include-in-header: 
      text: |
        \usepackage{mdframed}
        \usepackage{caption}
        \captionsetup[figure]{labelformat=empty}
        \captionsetup[table]{labelformat=empty}


