project:
  type: book
  output-dir: docs
book:
  title: "Exploring Data Science Education: From Tutorials to Assessment"
  subtitle: "Duke Statistical Science | Graduation with Distinction"
  date: last-modified
  date-format: long
  author: 
    - Evan Dragich
    - supervised by Dr. Mine Çetinkaya-Rundel, PhD.
  chapters:
    - index.qmd
    - 01-thesis-intro.qmd
    - 02-background.qmd
    - 03-development.qmd
    - 05-package.qmd
    - 06-discussion.qmd
    - 10-bibliography.qmd
    - 90-instrument.qmd
    - 91-graveyard.qmd
    - 92-package-examples.qmd

execute:
  echo: false
  warning: false

bibliography: thesis.bib
nocite: |
  @*

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 0
    number-depth: 0
    css: styles.css
  pdf:
    documentclass: scrreprt
    toc: true
    toc-depth: 0
    number-depth: 0


