
### Abstract {.unnumbered}

As data science (DS) continues to grow in popularity among university course offerings, it is becoming crucial to successfully measure students' learning outcomes in introductory courses. To do this requires an assessment which could additionally be used to evaluate pedagogical techniques or curriculum interventions in data science curriculum.

To develop a blueprint for the assessment, a multi-institutional team of statistics and data science education researchers identified common DS content (e.g., data wrangling, interpreting visualizations), drawing from published guidelines/recommendations and introductory DS syllabi. A draft of the assessment was written and used to conduct three think-aloud interviews with field-relevant faculty members. The interviews consisted of both open-ended brainstorming on the assessment's scope as well as individual examinations of each item for relevance, clarity, and efficacy in measuring the desired learning objective. Think-aloud interviews were also conducted with TAs of an introductory DS course to gauge item clarity and gain insight into the reasoning for their responses.

As well, given the recent rise in popularity of open source educational software, there is a growing demand for scalable DS pedagogical materials. Based on the Data Science in a Box introductory DS curriculum, we have developed an R package `dsbox` containing 10 interactive, self-contained, auto-graded tutorials covering concepts from basic data wrangling and visualization to simple modeling.

This work includes descriptions of the blueprint developed for both the assessment and package, as well as examples of assessment items and tutorials, and results from the faculty and student think aloud interviews. We also present next steps for the project including plans for larger scale piloting and further analyses.

### Goals {.unnumbered}

By sharing the work, we hope that participants will become familiar with an assessment they may use for designing intro data science curriculum or researching classroom innovations. We also hope that this instrument can serve as an inspiration or a starting point to be tailored by future researchers more specifically to their courses or to another discipline (e.g. by adding more programming concepts to better serve a computing-focused introductory data science class, etc.) We hope to officially release `dsbox` to CRAN by the end of the Spring 2023 semester, offering access to DS education to a wider community.
